version: "3.4"
services:
  app:
    container_name: alti
    build:
      context: .
      target: final
    environment:
      - CANVAS_API_URL
      - CANVAS_TOKEN
      - LTI_KEY
      - LTI_SECRET
      - TRUST_PROXY
    ports:
      - "${CI_APP_PORT}"
  e2e:
    container_name: cypress
    build: ./e2e
    depends_on:
      - app
    environment:
      - CI=1
      - NO_COLOR
      - APP_URL=${CI_APP_URL}
      - CYPRESS_baseUrl=${CI_CYPRESS_baseUrl}
      - LTI_KEY
      - LTI_SECRET
    volumes:
      - ./e2e/cypress:/app/cypress:rw
      - ./e2e/cypress.json:/app/cypress.json:ro
    command: npx cypress run